### ISSUE TITLE
do u dev for free?/

### ISSUE THREAD

**Issue by BLAST1718** [ByAlperenS/Fireball#1]

**Comment by ByAlperenS** [comment]
For the Fireball plugin?

**Comment by BLAST1718** [comment]
for my server and what does the fireball do?

**Comment by ByAlperenS** [comment]
I am already working on a server

**Comment by ByAlperenS** [comment]
fireball attachment allows flying using fireball

**Comment by ByAlperenS** [comment]
video link: https://www.youtube.com/watch?v=EliTZUAP5J0

**Comment by ByAlperenS** [comment]
I'm closing the issue

**Comment by BLAST1718** [comment]
i need a dev for free :(

**Comment by ByAlperenS** [comment]
unfortunately i can't

**Comment by BLAST1718** [comment]
also a suggestion make the

**Comment by BLAST1718** [comment]
fireball like in bedwars
